host and pass

diff --git a/XWing b/XWing
--- a/XWing
+++ b/XWing
@@ -1,26 +1,26 @@
 #!/bin/sh
-#PATH=$(cd "${0%/*}"; pwd):$PATH
-#CDIR="$(cd "${0%/*}"; pwd)"
+#TROJAN_HOST=
+#TROJAN_PASS=
 
-find_interface()
+iface()
 {
 	sdev=`route get example.com 2> /dev/null | grep interface`
 	sdev=${sdev:13}
 	while read -r line; do
 		echo $line | grep $sdev > /dev/null 2>&1
 		if [ $? = 0 ]; then
-			currentservice=${last_line:4}
+			IFACE=${last_line:4}
 			break
 		fi
 		last_line=$line
 	done <<< "$(networksetup -listnetworkserviceorder)"
 
-	if [ -z "$currentservice" ]; then
-	    >&2 echo "Could not find current service"
-	    exit 1
+	if [ -z "$IFACE" ]; then
+		>&2 echo "Could not find current service"
+		exit 1
 	fi	
 
-	echo "Current interface: $currentservice"
+	echo "Current interface: $IFACE"
 }
 
 usage()
@@ -34,25 +34,26 @@ usage()
 
 start()
 {
-	find_interface
-	networksetup -setsocksfirewallproxy $currentservice 127.0.0.1 1080
+	iface
+	networksetup -setsocksfirewallproxy $IFACE 127.0.0.1 1080
 
-	echo "{\"local_addr\":\"0.0.0.0\",\"local_port\":1080,\"remote_addr\":\"$2\",\"remote_port\":443,\"password\":[\"$3\"],\"log_level\":$1,\"ssl\":{\"verify\":false}}" > /tmp/trojan.conf
+	[ ! -z $2 ] && TROJAN_HOST=$2
+	[ ! -z $3 ] && TROJAN_PASS=$3
+	echo "{\"local_addr\":\"0.0.0.0\",\"local_port\":1080,\"remote_addr\":\"$TROJAN_HOST\",\"remote_port\":443,\"password\":[\"$TROJAN_PASS\"],\"log_level\":$1,\"ssl\":{\"verify\":false}}" > /tmp/trojan.conf
 	if [ $1 -ge 4 ]; then
 		nohup trojan -c /tmp/trojan.conf &> /tmp/trojan.log &
 	elif [ $1 -ge 2 ]; then
 		trojan -c /tmp/trojan.conf &
 	else
 		trojan -c /tmp/trojan.conf
-		networksetup -setsocksfirewallproxystate $currentservice off
+		networksetup -setsocksfirewallproxystate $IFACE off
 	fi
 }
 
 stop()
 {
-	find_interface
-	networksetup -setsocksfirewallproxystate $currentservice off
-
+	iface
+	networksetup -setsocksfirewallproxystate $IFACE off
 	killall trojan
 }
 
